// Artist → genre collection mapping (primary artist, case-insensitive). Unknown → Unsorted.
export const GENRES = {
  "Focus": ["FKJ","Tom Misch","Masego","Masego, FKJ","Joe Hertz","Mild Orange","Duñe, Crayon","Moods","Jordan Rakei","Men I Trust","Khruangbin","Nujabes","Bonobo","Tycho","Emancipator","Lane 8","Yppah","Blue Wednesday","Parcels","Cosmo Sheldrake","Still Woozy","Rex Orange County","Cuco","Boy Pablo","Jakob Ogawa","Mac Ayres","Tom Rosenthal","Ben Howard","José González","Novo Amor","Bon Iver","Sufjan Stevens"],
  "Classic Rock": ["Sting","Aerosmith","Bob Marley & The Wailers","Amy Winehouse","Jack Johnson","Backstreet Boys","Dire Straits","Pink Floyd","Queen","Eagles","AC/DC","The Police","Depeche Mode","The Rolling Stones","Oasis","The Beatles","Mark Knopfler","Elton John","America","Bill Withers","Chris Isaak","Eddie Vedder","John Mayer","Supertramp","The Who","Bob Dylan","Neil Young","The Animals","Jim Croce","Ten Years After","Buffalo Springfield","Led Zeppelin","Fleetwood Mac","Eric Clapton","David Bowie","Bruce Springsteen","Tom Petty","Creedence Clearwater Revival","Lynyrd Skynyrd","Guns N' Roses","Bon Jovi","Eurythmics","a-ha","Tears For Fears","Duran Duran","Alphaville","The Cure","Blur","The Verve","Smash Mouth","Caesars","Primus","The Doors","Deep Purple","Black Sabbath","Simon & Garfunkel","Cat Stevens","Toto","Journey","Dio"],
  "Alt & Indie": ["The White Stripes","Kings of Leon","KALEO","Mansionair","Marian Hill","Anouk","Pomme","Boulevard des Airs","Chloe Adams","Honors","alt-J","Arctic Monkeys","Radiohead","Muse","The Strokes","The Killers","Tame Impala","Cage The Elephant","Foster The People","Glass Animals","Milky Chance","Gorillaz","Coldplay","Two Door Cinema Club","The Neighbourhood","Foals","The xx","Giant Rooks","George Ezra","Måneskin","Temper City","The Fray","BENEE","Joji","Dominic Fike","Hippie Sabotage","Alfie Templeman","Big Wild","X Ambassadors","Bastille","Vance Joy","Hozier","Lord Huron","MGMT","Phoenix","Vampire Weekend","Of Monsters and Men","Mumford & Sons","The Lumineers","Portugal. The Man","Bishop Briggs","Two Feet","Dennis Lloyd","Lola Marsh","Noga Erez","Jane Bordeaux","theAngelcy","Garbage","Franz Ferdinand","Kasabian","Interpol","Bloc Party","Editors","The 1975","Imagine Dragons","Twenty One Pilots","Panic! At The Disco","Michele Morrone","Jordan Max","Rosenfeld"],
  "Rock": ["Linkin Park","Green Day","Red Hot Chili Peppers","Foo Fighters","Paramore","Metallica","System Of A Down","Rage Against The Machine","Rammstein","Nickelback","Skillet","My Chemical Romance","blink-182","Fall Out Boy","Nirvana","Audioslave","3 Doors Down","The All-American Rejects","John Frusciante","Evanescence","Breaking Benjamin","Three Days Grace","Papa Roach","Slipknot","Korn","Disturbed","Limp Bizkit","Sum 41","The Offspring","Weezer","Soundgarden","Pearl Jam","Alice In Chains","Stone Temple Pilots","Bush","Incubus","Deftones","Tool","A Perfect Circle","Chevelle","Seether","Shinedown","Rise Against","Billy Talent","Linkin Park, Kiiara","Bring Me The Horizon","Avenged Sevenfold","Bullet For My Valentine","Volbeat","Ghost","Royal Blood","Highly Suspect","Nothing But Thieves","Arctic Monkeys"],
  "Hip-Hop & Pop": ["Ozuna","Shakira","Internet Money","CJ","GIMS","Matisyahu","RACK","Emmit Fenn","Eminem","Billie Eilish","Drake","Sia","The Weeknd","Mac Miller","Kendrick Lamar","Post Malone","Stromae","BLACKPINK","Lil Nas X","Childish Gambino","Doja Cat","Dua Lipa","Travis Scott","Juice WRLD","Kanye West","JAŸ-Z","DJ Khaled","Macklemore","Macklemore & Ryan Lewis","Maroon 5","Ed Sheeran","Black Eyed Peas","Soulja Boy","benny blanco","blackbear","Khalid","Bad Bunny","Melanie Martinez","FINNEAS","BoyWithUke","Goody Grace","LAUV","Arizona Zervas","Jason Derulo","MAGIC!","Mahmood","CKay","Nelly","Michael Bublé","*NSYNC","Anderson .Paak","Harry Styles","Rupert Holmes","Saweetie","Charli xcx","Aya Nakamura","Maluma","Eddie Benjamin","Halsey","Ariana Grande","Justin Bieber","Shawn Mendes","Camila Cabello","Bruno Mars","Rihanna","Beyoncé","Lady Gaga","Taylor Swift","Olivia Rodrigo","Lizzo","SZA","Frank Ocean","Tyler, The Creator","J. Cole","Logic","NF","XXXTENTACION","Lil Peep","Lil Uzi Vert","21 Savage","Cardi B","Megan Thee Stallion","Nicki Minaj","Future","Migos","A$AP Rocky","Tyga","Wiz Khalifa","Snoop Dogg","Dr. Dre","50 Cent","2Pac","The Notorious B.I.G.","Nas","Hopsin","Joyner Lucas","Token","Dax","Lil Dicky","Jack Harlow","Doja Cat","Jonas Brothers","OneRepublic","Avril Lavigne","P!nk","Kesha","Katy Perry","Adele","Lorde","Lana Del Rey","Tones And I","Glass Animals, Shakur Ahmad","Rag'n'Bone Man","James Arthur","Lewis Capaldi","Sam Smith","Zayn","Troye Sivan","Conan Gray","Lauv"],
  "Psytrance & EDM": ["LUM!X","OVERWERK","Funtwo","Infected Mushroom","Avicii","KSHMR","Skrillex","David Guetta","Dimitri Vegas & Like Mike","Marshmello","Kygo","Martin Garrix","Tiësto","Pegboard Nerds","Bliss","Alle Farben","Ofenbach","Caravan Palace","Knife Party","Datsik","Virtual Riot","Benny Benassi","Astronaut","Bear Grillz","Vini Vici","Astrix","Ace Ventura","Skazi","Alok","Calvin Harris","Zedd","The Chainsmokers","Major Lazer","Diplo","Galantis","Swedish House Mafia","Axwell /\\ Ingrosso","Hardwell","Armin van Buuren","Above & Beyond","deadmau5","Eric Prydz","Fisher","Dom Dolla","Fred again..","Joel Corry","Jax Jones","Lucky Luke","ECHO","HUGEL","Francis Mercier","Rampa","Bakermat","Be Svendsen","Stavroz","Nitefreak","Keinemusik","TRFN","Soda","Marnik","Vairo","Joezi","Menumas","Monstercat","Robin Schulz","Felix Jaehn","Lost Frequencies","Sigala","Jonas Blue","Clean Bandit","Disclosure","Duke Dumont","Meduza","Topic","Regard","Imanbek","Purple Disco Machine","Hevi Levi","Dame Dame"],
  "Deutsch": ["Nullzweizwei","Bonez MC","187erz","Ufo361","Gzuz","Jalil","Maxwell","Joshi Mizu","187 Strassenbande","LX","Sa4","CRO","Nina Chuba","Mark Forster","JORIS","RAF Camora","Capital Bra","Apache 207","Shirin David","Luciano","Kontra K","Sido","Bushido","Kollegah","Farid Bang","Samra","Loredana","Juju","Trettmann","Casper","Marteria","Kraftklub","AnnenMayKantereit","Die Toten Hosen","Die Ärzte","Peter Fox","Seeed","Deichkind","Alligatoah","Prinz Pi","Cro","Max Giesinger","Wincent Weiss","Revolverheld","Clueso","Silbermond","Juli","Tim Bendzko","Johannes Oerding","Namika","Lea","Nico Santos","Alvaro Soler","Bausa","Kalim","Nimo","Mero","Eno","Summer Cem","KC Rebell","Azet","Zuna","Jamule","Miksu / Macloud","Haftbefehl","Celo & Abdi","Xatar","SSIO","Dardan","Nate57","Olexesh","Fler","Kool Savas","Eko Fresh","Massiv","Animus","Veysel","Play69","Sun Diego","SpongeBOZZ","Kianush","Montez","Lune","Monet192","badmómzjay","Eunique","Liz","Ayliva","Fridolin","Rin","Yung Hurn","Bibi & Tina","Specktors","Lukas Graham"],
  "Israeli Rock": ["TATRAN","Knesiyat Hasechel","Alma Zohar","Tuna","Eden Hason","Eviatar Banai","Mercedes Band","Full Trunk","Monica Sex","Beit Habubot","Ravid Plotnik","Hadag Nahash","Aviv Geffen","Mashina","Shlomo Artzi","Berry Sakharof","Fortisakharof","Girafot","Yoni Bloch","Ehud Banai","Shalom Hanoch","Arik Einstein","Yoni Rechter","Hasmachot","Mooki","Carakukly","Shabak Samech","Habiluim","Teapacks","Eifo HaYeled","Synergia","Mofa Haarnavot Shel Dr. Kasper","Red Band","Knesiyat Hasekhel","Tislam","Mashina","Ethnix","Rami Fortis","Dana Berger","Rona Kenan","Shlomi Shaban","Jasmin Moallem","Elai Botner","Ivri Lider","Sheygets","Alon Eder","Amir Dadon","Nathan Goshen","Guy Mazig","Yishay Swissa","Ran Danker","Bar Tzabary","Jacob Markman","Shai Nehaisi","Sagi Braitner","Narkis","Leyli","Kobi Aflalo","Omer Netzer","Avior Malasa","Arutz Hakibud","Cookie Levanna","Subliminal","Avihu Pinhasov Rhythm Club","E-Z","Eric Berman","Jimbo J","Shekel","Tamir Grinberg","Eliad","Idan Rafael Haviv","הפיל הכחול","רביב כנר","שחר סאול","נעם מיכאל","Roni Alter","Harel Skaat","Amir Ve Ben","Peer Tasi","Dudu Tassa","Ester Rada","Balkan Beat Box","Infected Mushroom, Bliss","Meir Ariel","Kaveret","Yehuda Poliker","Rita","Yehudit Ravitz","Hayehudim","Dag Nahash","Ninet Tayeb","Asaf Avidan","Geva Alon","Tamar Eisenman","Benaia Barabi","בניה ברבי","Nunu","Ran Nir","Yael Naim","Marina Maximilian","Keren Peles"],
  "Israeli Pop": ["Omer Adam","Osher Cohen","Static","Static & Ben El","Ben El Tavori","Idan Amedi","Eden Ben Zaken","Liran Danino","Anna Zak","חנן בן ארי","Ishay Ribo","Motty Steinmetz","Eden Alene","Doli & Penn","Stephane Legar","Noa Kirel","Eyal Golan","Moshe Peretz","Sarit Hadad","Dudu Aharon","Itay Levi","Nasrin Kadri","Agam Buhbut","Eliad Nahum","Kobi Peretz","Lior Narkis","Haim Moshe","Zohar Argov","Shlomi Shabat","Dikla","Ravid Plotnik, Jimbo J","Nes","Ness","סטילה","Stilla","Peer Tasi","Regev Hod","Ishay Levi","Yasmin Moallem","Odeya","Adir Gets","Roni Dalumi","Mergui","Nadav Guedj","Mickey Peretz","Omer Adam, Arisa","Netta","Dana International","Rita","Sarit Hadad","Ilanit","Margalit Tzan'ani","Ofra Haza","Shiri Maimon","Ninet","Harel Moyal","Itay Levi","Jasmin Moallem, Static","Yuval Dayan","Nunu","Dennis Lloyd, Eden Hason"],
};
const lookup = new Map();
for (const [g, arts] of Object.entries(GENRES)) for (const a of arts) if (!lookup.has(a.toLowerCase())) lookup.set(a.toLowerCase(), g);
const HEB = /[֐-׿]/;
export function classify(track) {
  const primary = track.artists.split(", ")[0];
  const g = lookup.get(primary.toLowerCase()) ?? lookup.get(track.artists.toLowerCase());
  if (g) return g;
  if (HEB.test(track.name) || HEB.test(track.artists)) return "Israeli Rock"; // Hebrew-titled & unknown → Israeli bucket (user triages)
  return "Unsorted";
}
