import { spotify } from "../src/spotify.js";
import { announceBudget, isBudgetError } from "./lib.js";
import { readFileSync } from "node:fs";
const lib = JSON.parse(readFileSync(process.argv[2], "utf8"));
const have = new Set([...lib.liked, ...Object.values(lib.playlists).flatMap(p => p.tracks)].flatMap(t => t.artists.split(", ").map(a => a.toLowerCase())));
// [artist, track] — bridges noted per block
const S = [
 // --- from Dire Straits / Pink Floyd / classic rock lineage
 ["Steely Dan","Do It Again"],["Gerry Rafferty","Baker Street"],["Chris Rea","On the Beach"],["J.J. Cale","Call Me the Breeze"],["Little Feat","Dixie Chicken"],["Talking Heads","This Must Be the Place"],["Roxy Music","More Than This"],["Peter Gabriel","Solsbury Hill"],["Traffic","The Low Spark of High Heeled Boys"],["Camel","Lady Fantasy"],["Porcupine Tree","Trains"],["Riverside","Second Life Syndrome"],["Steven Wilson","The Raven That Refused to Sing"],["Opeth","Harvest"],["Anathema","Untouchable Part 1"],["Marillion","Kayleigh"],["Jethro Tull","Locomotive Breath"],["Wilco","Jesus, Etc."],["My Morning Jacket","Golden"],["Ryan Adams","New York, New York"],["Jason Isbell","Cover Me Up"],["The National","Bloodbuzz Ohio"],["Big Thief","Not"],["Fleet Foxes","White Winter Hymnal"],["Band of Horses","The Funeral"],
 // --- alt-J / Radiohead / Arctic Monkeys bridges
 ["Everything Everything","Cough Cough"],["Django Django","Default"],["Glass Animals","Gooey"],["Unknown Mortal Orchestra","Multi-Love"],["King Krule","Easy Easy"],["Black Country, New Road","Track X"],["Squid","Narrator"],["IDLES","Mother"],["Shame","One Rizla"],["Yard Act","The Overload"],["Dry Cleaning","Scratchcard Lanyard"],["Parquet Courts","Wide Awake"],["Courtney Barnett","Pedestrian at Best"],["Car Seat Headrest","Drunk Drivers/Killer Whales"],["Alvvays","Archie, Marry Me"],["Beach House","Space Song"],["Mac DeMarco","Chamber of Reflection"],["Kurt Vile","Pretty Pimpin"],["Sufjan Stevens","Chicago"],["Grizzly Bear","Two Weeks"],["Animal Collective","My Girls"],["Broken Social Scene","Anthems for a Seventeen Year-Old Girl"],["Modest Mouse","Float On"],["Built to Spill","Carry the Zero"],["Pavement","Cut Your Hair"],["Sonic Youth","Teen Age Riot"],["Pixies","Where Is My Mind?"],["The Smiths","There Is a Light That Never Goes Out"],["Joy Division","Love Will Tear Us Apart"],["Echo & the Bunnymen","The Killing Moon"],
 // --- heavy / Linkin Park / SOAD / Rammstein bridges
 ["Gojira","Flying Whales"],["Mastodon","Blood and Thunder"],["Tool","Schism"],["Karnivool","Simple Boy"],["Periphery","Scarlet"],["Architects","Doomsday"],["Loathe","Two-Way Mirror"],["Polyphia","Playing God"],["Lorna Shore","To the Hellfire"],["Electric Callboy","Hypa Hypa"],["Eisbrecher","Verrückt"],["Oomph!","Augen auf!"],["Ghost","Square Hammer"],["Alice in Chains","Would?"],["Faith No More","Epic"],["Incubus","Drive"],["Glassjaw","Ape Dos Mil"],["Thrice","The Earth Will Shake"],["Coheed and Cambria","Welcome Home"],["Mr. Bungle","Retrovertigo"],["Orphaned Land","Sapari"],["Amaranthe","Drop Dead Cynical"],["Babymetal","Gimme Chocolate!!"],["Man with a Mission","Remember Me"],["Maximum the Hormone","Zetsubou Billy"],
 // --- psytrance / Infected Mushroom lineage
 ["Hallucinogen","LSD"],["Juno Reactor","Pistolero"],["Talamasca","Dreams"],["Hilight Tribe","Free Tibet"],["Neelix","Expect What"],["Liquid Soul","Devotion"],["Captain Hook","Human Design"],["Ranji","Fly High"],["Blastoyz","Mandala"],["Berg","Mindscape"],["Ace Ventura","Going Up"],["Zyce","Love Forever"],["Protoculture","Refractions"],["Shpongle","Dorset Perception"],["Younger Brother","Magic Monkey Juice"],["Entheogenic","Pagan Dream Machine"],["Carbon Based Lifeforms","Photosynthesis"],["Solar Fields","Sol"],["Boris Brejcha","Gravity"],["Stephan Bodzin","Singularity"],["Tale of Us","Nova Two"],["Adriatique","Voices From the Dawn"],["ARTBAT","Horizon"],["Anyma","Eternity"],["Bicep","Glue"],["Jamie xx","Gosh"],["Caribou","Can't Do Without You"],["Moderat","A New Error"],["Apparat","Goodbye"],["Paul Kalkbrenner","Sky and Sand"],
 // --- Israeli you don't have
 ["Dudu Aharon","מתאים לי"],["Eyal Golan","יפה שלי"],["Itay Levi","עיניים"],["Agam Buhbut","תשמרי"],["Nasrin Kadri","תרקוד"],["Ravid Kahalani","Hawalti"],["Yemen Blues","Jat Mahibathi"],["A-WA","Habib Galbi"],["Balkan Beat Box","Hermetico"],["Shotei Hanevua","כבר יום"],["Ninet Tayeb","Superstar"],["Asaf Avidan","Reckoning Song"],["Geva Alon","Get Closer"],["Tamar Eisenman","Kisses"],["Rotem Cohen","הכי יפה בעולם"],["Yehuda Levi","ינשוף"],["Ran Danker","פלסטר"],["Peled","לא רוצה להתבגר"],["Ravid Plotnik","שי"],["Tuna","תחנה מרכזית"],["Nechi Nech","מניאק"],["Cohen@Mushon","רק תמצא"],["Shekel","ספסל"],["Lukach","שבת בבוקר"],["Echo","ירושלים"],["Kafe Shahor Hazak","אלה דווקא החיים"],["Hatikva 6","מוצאי שבת"],["Teddy Neguse","אהבה"],["Jimbo J","תל אביב"],["Tamir Grinberg","אין לי ארץ אחרת"],["Mergui","מאמא"],["Odeya","הולכת איתך"],["Yuval Dayan","מכתבים"],["Nadav Guedj","Golden Boy"],["Noa Kirel","Unicorn"],["Marina Maximilian","בוא נלך"],["Keren Peles","מבול"],["Rona Kenan","עתיד מתוק"],["Ehud Banai","בלוז כנעני"],["Meir Banai","געגוע"],["Yehudit Ravitz","ארץ טרופית יפה"],
 // --- French
 ["Stromae","Santé"],["Angèle","Balance ton quoi"],["Aya Nakamura","Djadja"],["Christine and the Queens","Tilted"],["Indila","Dernière danse"],["Gims","Bella"],["Zaz","Je veux"],["Noir Désir","Le vent nous portera"],["Serge Gainsbourg","Bonnie and Clyde"],["Jacques Brel","Ne me quitte pas"],["Édith Piaf","Non, je ne regrette rien"],["Daft Punk","Around the World"],["Justice","D.A.N.C.E."],["Air","Sexy Boy"],["M83","Midnight City"],["Phoenix","Lisztomania"],["L'Impératrice","Vanille fraise"],["Polo & Pan","Canopée"],["Vitalic","Poney Pt. 1"],["Sébastien Tellier","La Ritournelle"],["MC Solaar","Caroline"],["IAM","Je danse le mia"],["Orelsan","La fête est finie"],["Nekfeu","On verra"],["Lomepal","Trop beau"],["Ben Mazué","Quand je marche"],["Pomme","Anxiété"],["Clara Luciani","La grenade"],["Juliette Armanet","Le dernier jour du disco"],["Yseult","Corps"],
 // --- Spanish / Portuguese / Latin
 ["Rosalía","MALAMENTE"],["C. Tangana","Tú Me Dejaste De Querer"],["Bad Bunny","Tití Me Preguntó"],["Héroes del Silencio","Entre dos tierras"],["Jarabe de Palo","La Flaca"],["Manu Chao","Clandestino"],["Soda Stereo","De Música Ligera"],["Gustavo Cerati","Crimen"],["Café Tacvba","Eres"],["Zoé","Labios Rotos"],["Natalia Lafourcade","Hasta la Raíz"],["Mon Laferte","Tu Falta de Querer"],["Bomba Estéreo","Soy Yo"],["Calle 13","Latinoamérica"],["Residente","René"],["Silvio Rodríguez","Ojalá"],["Buena Vista Social Club","Chan Chan"],["Caetano Veloso","Sozinho"],["Gilberto Gil","Aquele Abraço"],["Jorge Ben Jor","Mas Que Nada"],["Seu Jorge","Burguesinha"],["Marisa Monte","Ainda Bem"],["Anitta","Envolver"],["Bacao Rhythm & Steel Band","Bacao Suave"],["Rodrigo Amarante","Tuyo"],["Bebel Gilberto","Samba da Bênção"],["Tom Jobim","Águas de Março"],["Cesária Évora","Sodade"],["Salvador Sobral","Amar pelos dois"],["Mariza","Ó Gente da Minha Terra"],
 // --- Arabic / Turkish / Mediterranean
 ["Fairuz","Kifak Inta"],["Umm Kulthum","Enta Omri"],["Mashrou' Leila","Fasateen"],["Cairokee","Ethbat Makanak"],["Sharmoofers","Khamsa Santy"],["Wegz","El Bakht"],["Marwan Moussa","Sheraton"],["Saint Levant","Very Few Friends"],["Elyanna","Mama Eh"],["Altın Gün","Goca Dünya"],["Sezen Aksu","Gülümse"],["Tarkan","Şımarık"],["Duman","Senden Daha Güzel"],["maNga","Dursun Zaman"],["Mabel Matiz","Ya Bu İşler Ne"],["Ceza","Holocaust"],["Ezhel","Geceler"],["Ibrahim Maalouf","Beirut"],["Anouar Brahem","The Astounding Eyes of Rita"],["Tinariwen","Tenere Taqqim Tossam"],["Mdou Moctar","Afrique Victime"],["Souad Massi","Raoui"],["Cheb Khaled","Aïcha"],["Rachid Taha","Ya Rayah"],["Omar Souleyman","Warni Warni"],["Acid Arab","Stil"],["Bombino","Tar Hani"],["Yasmine Hamdan","Beirut"],["Dudu Tassa & Jonny Greenwood","Djit Nishrab"],["Eli Keszler","Vega"],
 // --- Italian / German / Dutch / Nordic
 ["Måneskin","Zitti e buoni"],["Lucio Dalla","Caruso"],["Fabrizio De André","La canzone di Marinella"],["Pino Daniele","Napule è"],["Mahmood","Soldi"],["Calcutta","Paracetamolo"],["Coez","La musica non c'è"],["Kraftklub","Ich will nicht nach Berlin"],["AnnenMayKantereit","Oft gefragt"],["Peter Fox","Haus am See"],["Seeed","Ding"],["Deichkind","Leider geil"],["Trettmann","Grauer Beton"],["Bilderbuch","Maschin"],["Wanda","Bologna"],["Die Toten Hosen","Tage wie diese"],["Rammstein","Deutschland"],["Faber","Wem du's heute kannst besorgen"],["Sigrid","Strangers"],["Aurora","Runaway"],["Kaizers Orchestra","Hjerteknuser"],["Sigur Rós","Hoppípolla"],["Of Monsters and Men","Little Talks"],["Ásgeir","King and Cross"],["First Aid Kit","Emmylou"],["The Tallest Man on Earth","The Gardener"],["Mew","Comforting Sounds"],["Efterklang","Modern Drift"],["Agnes Obel","Riverside"],["Lykke Li","I Follow Rivers"],
 // --- Korean / Japanese / Asia
 ["BTS","Dynamite"],["NewJeans","Super Shy"],["IU","Blueming"],["Hyukoh","Wi Ing Wi Ing"],["Se So Neon","Long Dream"],["DPR IAN","So Beautiful"],["Crush","Beautiful"],["Zion.T","Yanghwa BRDG"],["Epik High","Fly"],["Fishmans","Long Season"],["Lamp","ゆめうつつ"],["Tatsuro Yamashita","Sparkle"],["Mariya Takeuchi","Plastic Love"],["Anri","Remember Summer Days"],["RADWIMPS","Sparkle"],["Yoasobi","Idol"],["Ado","Usseewa"],["King Gnu","Hakujitsu"],["Vaundy","Kaiju no Hanauta"],["Cornelius","Star Fruits Surf Rider"],["Nujabes","Feather"],["Toe","Goodbye"],["Mono","Ashes in the Snow"],["Kikagaku Moyo","Dripping Sun"],["Phum Viphurit","Lover Boy"],["Sunset Rollercoaster","My Jinji"],["9m88","Airplane Mode"],["Anik Khan","Dreamer"],["Prateek Kuhad","cold/mess"],["Arijit Singh","Tum Hi Ho"],
 // --- Afrobeats / African / Caribbean
 ["Burna Boy","Last Last"],["Wizkid","Essence"],["Rema","Calm Down"],["Tems","Free Mind"],["Asake","Lonely at the Top"],["Fela Kuti","Water No Get Enemy"],["Tony Allen","Afro Disco Beat"],["Amadou & Mariam","Sabali"],["Ali Farka Touré","Ai Du"],["Salif Keita","Madan"],["Angélique Kidjo","Agolo"],["Black Coffee","Drive"],["Nomcebo Zikode","Jerusalema"],["Mafikizolo","Khona"],["Sauti Sol","Suzanna"],["Diamond Platnumz","Jeje"],["Koffee","Toast"],["Protoje","Who Knows"],["Chronixx","Here Comes Trouble"],["Damian Marley","Welcome to Jamrock"],["Toots & The Maytals","Pressure Drop"],["Jimmy Cliff","Many Rivers to Cross"],["Skip Marley","Slow Down"],["Kabaka Pyramid","Well Done"],["Tiken Jah Fakoly","Plus rien ne m'étonne"],
 // --- Hip-hop / pop adjacent to Eminem / Billie / Mac Miller
 ["Kendrick Lamar","HUMBLE."],["Denzel Curry","Ultimate"],["JID","Surround Sound"],["Anderson .Paak","Come Down"],["Loyle Carner","Ottolenghi"],["Little Simz","Woman"],["Dave","Location"],["slowthai","Doorman"],["Aminé","Caroline"],["Smino","Anita"],["Saba","Photosynthesis"],["Noname","Diddy Bop"],["Vince Staples","Norf Norf"],["Earl Sweatshirt","Chum"],["Danny Brown","Ain't It Funny"],["Run the Jewels","Legend Has It"],["Atmosphere","Sunshine"],["Aesop Rock","None Shall Pass"],["MF DOOM","Rapp Snitch Knishes"],["Mos Def","Umi Says"],["Clairo","Bags"],["Phoebe Bridgers","Motion Sickness"],["Mitski","Nobody"],["Japanese Breakfast","Be Sweet"],["Remi Wolf","Photo ID"],["Dominic Fike","3 Nights"],["Omar Apollo","Evergreen"],["Steve Lacy","Bad Habit"],["Yves Tumor","Gospel for a New Century"],["Arlo Parks","Hope"],
 // --- funk / soul / jazz bridges from FKJ / Tom Misch
 ["Vulfpeck","Dean Town"],["Cory Wong","Meditation"],["Jungle","Busy Earnin'"],["Hiatus Kaiyote","Red Room"],["Moonchild","The List"],["Tom Misch","Disco Yes"],["Kaytranada","10%"],["Toro y Moi","Ordinary Pleasure"],["Jamiroquai","Virtual Insanity"],["Roy Ayers","Everybody Loves the Sunshine"],["Herbie Hancock","Chameleon"],["Kamasi Washington","Street Fighter Mas"],["Robert Glasper","Afro Blue"],["BadBadNotGood","Time Moves Slow"],["Snarky Puppy","Lingus"],["GoGo Penguin","Raven"],["Nils Frahm","All Melody"],["Ludovico Einaudi","Nuvole Bianche"],["Max Richter","On the Nature of Daylight"],["Hania Rani","Glass"],
];
const existing = (await spotify.listPlaylists()).find(p => p.name === "🧭 Explore");
const pl = existing ?? await spotify.createPlaylist({ name: "🧭 Explore", description: "Suggestions · artists you have 0 songs from · many languages" });
const already = new Set((await spotify.getPlaylist(pl.id)).tracks.map(t => t.artists.split(", ")[0].toLowerCase()));
const norm = s => s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
announceBudget(S.length);
let batch = [], added = 0, skipped = 0, miss = [], stopped = false;
const flush = async () => { if (!batch.length) return; const r = await spotify.addTracks(pl.id, batch, { dedupe: false }); added += r.added; batch = []; console.log(`progress: ${added} added, ${miss.length} not found`); };
for (const [artist, track] of S) {
  if (have.has(artist.toLowerCase()) || already.has(artist.toLowerCase())) { skipped++; continue; }
  let res;
  try { res = await spotify.search(`${track} ${artist}`, "track", 5); } catch (e) { if (isBudgetError(e)) { console.log("stopping:", e.message); stopped = true; break; } miss.push(`${artist} – ${track}`); continue; }
  const t = res.find(r => norm(r.artists).includes(norm(artist)) && !/karaoke|tribute|cover/i.test(r.artists + r.album));
  t ? batch.push(t.id) : miss.push(`${artist} – ${track}`);
  if (batch.length >= 15) await flush();
}
await flush();
console.log(`${stopped ? "PAUSED (rerun to resume)" : "DONE"} added ${added} | skipped ${skipped} | not found ${miss.length}`);
console.log("not found:", miss.join(" | "));
