import { spotify } from "../src/spotify.js";
import { announceBudget, isBudgetError } from "./lib.js";
const S = [
 // global TikTok / charts 2024–early 2026
 ["Sabrina Carpenter","Espresso"],["Sabrina Carpenter","Manchild"],["Chappell Roan","Good Luck, Babe!"],["Chappell Roan","The Subway"],["Billie Eilish","BIRDS OF A FEATHER"],["Kendrick Lamar","Not Like Us"],["Kendrick Lamar","luther"],["Lady Gaga","Die With A Smile"],["Lady Gaga","Abracadabra"],["ROSÉ","APT."],["Benson Boone","Beautiful Things"],["Benson Boone","Mystical Magical"],["Teddy Swims","Lose Control"],["Hozier","Too Sweet"],["Charli xcx","360"],["Charli xcx","Apple"],["Doechii","DENIAL IS A RIVER"],["Bad Bunny","DtMF"],["Bad Bunny","NUEVAYoL"],["Lola Young","Messy"],["Gracie Abrams","That's So True"],["Addison Rae","Diet Pepsi"],["Addison Rae","Fame Is a Gun"],["Alex Warren","Ordinary"],["sombr","back to friends"],["sombr","undressed"],["Olivia Dean","Man I Need"],["Tate McRae","Sports car"],["Djo","End of Beginning"],["Artemas","i like the way you kiss me"],["Tommy Richman","MILLION DOLLAR BABY"],["Shaboozey","A Bar Song (Tipsy)"],["Myles Smith","Stargazing"],["Gigi Perez","Sailor Song"],["Ravyn Lenae","Love Me Not"],["Lorde","What Was That"],["Justin Bieber","DAISIES"],["Drake","NOKIA"],["Tyla","Water"],["Tyla","PUSH 2 START"],["HUNTR/X","Golden"],["Saja Boys","Soda Pop"],["Travis Scott","FE!N"],["Playboi Carti","EVIL J0RDAN"],["Yeat","IDGAF"],["Ken Carson","Fighting My Demons"],["Central Cee","BAND4BAND"],["Fred again..","adore u"],["Dom Dolla","Dreamin"],["FISHER","Losing It"],["Peggy Gou","1+1=11"],["Disclosure","She's Gone, Dance On"],["Jorja Smith","Little Things"],["Raye","Escapism."],["PinkPantheress","Illegal"],["Ice Spice","Munch"],["Tinashe","Nasty"],["Sexyy Red","Get It Sexyy"],["GloRilla","TGIF"],["Morgan Wallen","I Had Some Help"],["Post Malone","Pour Me A Drink"],["Zach Bryan","Something in the Orange"],["Noah Kahan","Stick Season"],["Hozier","Northern Attitude"],["Chase & Status","Baddadan"],["Bou","Closer"],["Hamdi","Skanka"],["Skrillex","Rumble"],["Kaytranada","Witchy"],["The Marías","No One Noticed"],["Laufey","From The Start"],["Beabadoobee","Glue Song"],["d4vd","Romantic Homicide"],["Conan Gray","Heather"],["Mk.gee","Alesis"],["Bôa","Duvet"],["Wave to Earth","bad"],["Cigarettes After Sex","Cry"],["Ethel Cain","American Teenager"],["Rosalía","Berghain"],["Bad Gyal","Chulo"],["Feid","LUNA"],["Rauw Alejandro","Tú Con Él"],["Karol G","Si Antes Te Hubiera Conocido"],["Peso Pluma","Ella Baila Sola"],["Fuerza Regida","TQM"],["Rema","Ozeba"],["Ayra Starr","Commas"],["Asake","Active"],["Burna Boy","TaTaTa"],["aespa","Whiplash"],["LE SSERAFIM","Crazy"],["NewJeans","How Sweet"],["Jung Kook","Seven"],["Stray Kids","Chk Chk Boom"],["Jennie","like JENNIE"],["LISA","Born Again"],["Creepy Nuts","Bling-Bang-Bang-Born"],["YOASOBI","Idol"],["Fujii Kaze","Shinunoga E-Wa"],
 // Israeli Gen-Z 2024–2026
 ["Noa Kirel","Unicorn"],["Eden Golan","Hurricane"],["Yuval Raphael","New Day Will Rise"],["Anna Zak","בוא"],["Odeya","יאללה"],["Peer Tasi","גלידה"],["Mergui","הביתה"],["Eden Hason","באמצע הלילה"],["Osher Cohen","באמת של האמת"],["Ravid Plotnik","הכל דבש"],["Tuna","משהו חדש"],["Jasmin Moallem","אורות"],["Nunu","דרך"],["Eden Ben Zaken","מלכת השושנים"],["Agam Buhbut","לב שבור"],["Shahar Saul","שיר אהבה"],["Roni Dalumi","מלך"],["Itay Levi","אמא"],["Eliad","ים של אהבה"],["Omer Adam","מודה אני"],["Static & Ben El","טודו בום"],["Stephane Legar","Comme Ci Comme Ça"],["Peled","אהבה חדשה"],["Jimbo J","ישראלי"],["Shekel","עיר"],["Teddy Neguse","חופש"],["Ness & Stilla","מחנס"],["Idan Raichel","ילדה"],["Hanan Ben Ari","ויקיפדיה"],["Ishay Ribo","סיבת הסיבות"],["Full Trunk","עיניים"],["Dudu Faruk","פיקודי"],["Tamir Grinberg","נדודי שינה"],["Nadav Guedj","מלכה"],["Netta","Toy"],["Noa Kirel","Bad Girl"],["Anna Zak","היפה בעולם"],["Odeya","סיפור ישן"],["Adir Gets","סעי לי"],["Dennis Lloyd","Nevermind"],
];
const ex = (await spotify.listPlaylists()).find(p => p.name === "🚗 Gen Z");
const pl = ex ?? await spotify.createPlaylist({ name: "🚗 Gen Z", description: "What's playing now (late 2024 → early 2026) · driving with Gen Z" });
const already = new Set((await spotify.getPlaylist(pl.id)).tracks.map(t => t.id));
const norm = s => s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
announceBudget(S.length);
let batch = [], added = 0, miss = [], stopped = false;
const flush = async () => { if (!batch.length) return; added += (await spotify.addTracks(pl.id, batch, { dedupe: false })).added; batch = []; console.log(`progress: ${added} added`); };
for (const [artist, track] of S) {
  let res; try { res = await spotify.search(`${track} ${artist}`, "track", 5); } catch (e) { if (isBudgetError(e)) { console.log("stopping:", e.message); stopped = true; break; } miss.push(`${artist} – ${track}`); continue; }
  const t = res.find(r => norm(r.artists).includes(norm(artist.split(" & ")[0])) && !/karaoke|tribute|cover/i.test(r.artists + r.album));
  if (t && !already.has(t.id)) { batch.push(t.id); already.add(t.id); } else if (!t) miss.push(`${artist} – ${track}`);
  if (batch.length >= 15) await flush();
}
await flush();
console.log(`${stopped ? "PAUSED (rerun to resume)" : "DONE"} added ${added} | not found ${miss.length}`); console.log("not found:", miss.join(" | "));
