import { spotify } from "../src/spotify.js";
import { readFileSync } from "node:fs";
const lib = JSON.parse(readFileSync(process.argv[2], "utf8"));
const ERA = ["linkin park","green day","eminem","blink-182","black eyed peas","soulja boy","smash mouth","*nsync","backstreet boys","avicii","nickelback","3 doors down","skillet","the all-american rejects","the fray","fall out boy","my chemical romance","panic! at the disco","paramore","evanescence","system of a down","rage against the machine","red hot chili peppers","foo fighters","coldplay","gorillaz","the killers","the strokes","kanye west","jaÿ-z","50 cent","nelly","maroon 5","rihanna","lady gaga","katy perry","kesha","david guetta","tiësto","swedish house mafia","owl city","the white stripes","kings of leon","oasis","blur","muse","radiohead","audioslave","metallica","rammstein","infected mushroom","subliminal","teapacks","shabak samech","hadag nahash","eifo hayeled","hayehudim","mofa haarnavot shel dr. kasper","ivri lider","beit habubot","monica sex","mashina","aviv geffen","shlomo artzi","eyal golan","sarit hadad","static","mooki","shotei hanevua","synergia","habiluim","girafot","fortisakharof","ethnix","tislam"];
const PICKS = ["Coldplay Yellow","Gorillaz Clint Eastwood","Outkast Hey Ya!","Evanescence Bring Me to Life","Kings of Leon Sex on Fire","MGMT Kids","Gnarls Barkley Crazy","Amy Winehouse Rehab","Daft Punk One More Time","Sean Paul Temperature","Shaggy It Wasn't Me","Nelly Furtado Promiscuous","Rihanna Umbrella","Lady Gaga Poker Face","Kesha TiK ToK","LMFAO Party Rock Anthem","Flo Rida Low","Owl City Fireflies","The Killers Mr. Brightside","Franz Ferdinand Take Me Out","Kaiser Chiefs Ruby","The Fratellis Chelsea Dagger","Arctic Monkeys I Bet You Look Good on the Dancefloor","Bloc Party Banquet","Yeah Yeah Yeahs Maps","Jet Are You Gonna Be My Girl","The Darkness I Believe in a Thing Called Love","Crazy Town Butterfly","Papa Roach Last Resort","Limp Bizkit Rollin'","Sum 41 Fat Lip","Simple Plan Welcome to My Life","Good Charlotte The Anthem","Bowling for Soup 1985","Hoobastank The Reason","Lifehouse Hanging by a Moment","The Calling Wherever You Will Go","Snow Patrol Chasing Cars","Keane Somewhere Only We Know","James Blunt You're Beautiful","Akon Smack That","T.I. Whatever You Like","Usher Yeah!","Eminem Without Me","50 Cent In da Club","Subliminal תקווה","Teapacks יושבים בבית קפה","Ivri Lider בוא","Infected Mushroom Becoming Insane","Shotei Hanevua המסע","Beit Habubot מחר","Eifo HaYeled אולי","Hadag Nahash לא פראיירים","Mooki מדינה קטנה","Static Tzfon Mezrah","Synergia ג'ולייטה"];
const pool = new Map(); for (const t of [...lib.liked, ...Object.values(lib.playlists).flatMap((p) => p.tracks)]) pool.set(t.id, t);
const fromLib = [...pool.values()].filter((t) => ERA.includes(t.artists.split(", ")[0].toLowerCase())).map((t) => t.id);
const pl = await spotify.createPlaylist({ name: "נוסטלגיה", description: "2000–2012 · the growing-up years" });
const found = [], miss = [];
for (const q of PICKS) { const t = (await spotify.search(q, "track", 1))[0]; t ? found.push(t) : miss.push(q); }
console.log("picks:", found.map((t) => `${t.name} – ${t.artists}`).join(" | "));
if (miss.length) console.log("missing:", miss.join(" | "));
console.log(await spotify.addTracks(pl.id, [...fromLib, ...found.map((t) => t.id)]), "from library:", fromLib.length);
